apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-agent-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s/jira-agent
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.k8s.boundWorker }}