apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.jira.service.type }}
  selector:
    app: jira
  ports:
    - port: {{ .Values.jira.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.jira.service.nodePort }}