apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-data-pvc
spec:
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.jira.persistence.size }}