apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 20Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: ""

  claimRef:
    namespace: atlassian
    name: postgres-data-pvc

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/k8s/postgres-data
    type: DirectoryOrCreate

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.k8s.boundWorker }}