apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-jira
  template:
    metadata:
      labels:
        app: postgres-jira
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jira-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jira-db-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: jira-db-secret
                  key: POSTGRES_DB

          ports:
            - containerPort: 5432

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc