apiVersion: v1
kind: PersistentVolumeClaim
namespace: {{ .Values.namespace }}
metadata:
  name: postgres-data-pvc
spec:
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}